### ISSUE TITLE
Include a dummy story to the template

### ISSUE THREAD

**Issue by jonniebigodes** [dannyhw/expo-template-storybook-tutorial#1]
While going through the example's code and usage i stumbled across one small item that requires a bit of attention. Instead of including the Task component/story file we could go with a dummy button or an input component, just to offer something out of the box when the user installs the template. The reasoning behind this is that with the introduction of the Task component /story we're basically bypassing part of the [Simple Component](https://www.learnstorybook.com/intro-to-storybook/react-native/en/simple-component/) chapter. 

Once more and i can't stress this enough, thank you very much for the time and effort you've been putting into Storybook for React Native. 

Stay safe¬

**Comment by dannyhw** [comment]
@jonniebigodes will work on this soon. I'll add some kind of simple button or something in it's place.

**Comment by jonniebigodes** [comment]
That's great. Let me know when you have something and we'll move from there :)

Stay safe

**Comment by dannyhw** [comment]
closed by #2, I've also released this to npm with v0.0.3 so it should now be usable with the expo init command
